#!/bin/sh

#loadkeys es
timedatectl set-ntp true
umount /mnt 2>/dev/null
pacman -Sy --needed --noconfirm dialog

ping -c 1 google.com || (dialog --colors --title "\Z1ERROR" --msgbox "\nNo tienes conexión a internet.\n\nPara instalar el sistema operativo es necesario estar conectado a internet.\n\nPara conectarse a una red wifi use el comando:\n> iwctl --passphrase *contraseña* station wlan0 connect *wifi*\n\nPara una red cableada simplemente conecte la computadora con un cable ethernet." 0 0 && exit)
# iwctl station wlan0 get-networks

discos=$(lsblk -l | grep "disk" | awk '{print $1" "$4}')
disco=$(dialog --no-cancel --menu "Escoja el disco donde se instalará arcarium:" 0 0 0 $discos --output-fd 1)
cfdisk "/dev/$disco"
sleep 0.1

discos=$(lsblk -l | grep "part" | awk '{print $1" "$4}')
while [ -z "$arranque" ] || [ -z "$sistema" ] || [ "$arranque" = "$sistema" ]; do
	arranque=$(dialog --no-cancel --menu "Escoja una partición para almacenar el sistema de arranque:\n\n(Esta partición suele pesar entre 128MB y 512MB)" 0 0 0 $discos --output-fd 1)
	sistema=$(dialog --no-cancel --menu "Escoja una partición para almacenar el sistema operativo:\n\n(Esta partición almacenará todos los archivos y programas)" 0 0 0 $discos --output-fd 1)
	[ -z "$arranque" ] && dialog --msgbox "No se ha seleccionado ninguna partición para el sistema de arranque.\n\nEs necesario una partición de arranque para poder iniciar el sistema operativo." 0 0
	[ -z "$sistema" ] && dialog --msgbox "No se ha seleccionado ninguna partición para el sistema operativo.\n\nEs necesario una partición para el sistema operativo por obvias razones." 0 0
	[ -n "$arranque" ] && [ -n "$sistema" ] && [ "$arranque" = "$sistema" ] &&
		dialog --msgbox "Las particiones para el sistema de arranque y para el sistema operativo no pueden ser la misma.\n\nEn caso de solo haber una partición, cierre el programa con Control + C, cree las particiones con 'cfdisk /dev/{disco a partir}' y vuelva a ejecutar este programa." 0 0
done

dialog --colors --infobox "\Z4Creando sistema de archivos" 10 60
mkfs.fat -F 32 "/dev/$arranque" >/dev/null
mkfs.btrfs -f "/dev/$sistema" >/dev/null

dialog --colors --infobox "\Z4Montando partición" 10 60
mount "/dev/$sistema" /mnt

dialog --colors --infobox "\Z4Iniciando instalanción de paquetes esenciales." 10 60
pacstrap -K /mnt base base-devel linux linux-firmware dhcpcd networkmanager git neovim btrfs-progs dosfstools ntfs-3g grub efibootmgr dialog fzf exa scrot socat sxhkd sxiv tree mpv xclip xwallpaper zathura zathura-pdf-mupdf jq vorbis-tools unrar unzip zip alsa-utils brightnessctl clipmenu dunst zsh zsh-syntax-highlighting dash firefox-i18n-es-es gparted htop inetutils net-tools newsboat perl-image-exiftool openssh noto-fonts-cjk noto-fonts-emoji otf-cascadia-code ttf-liberation rustup linux-headers xorg xorg-xinit picom lxappearance xdg-user-dirs pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber libnotify 2>/dev/null >/dev/null &
descarga=$!

controlador=$(dialog --colors --no-cancel --menu "Escoja su targeta gráfica:" 0 0 0 \
	1 "Nvidia" \
	2 "Intel" \
	3 "AMD" \
	--output-fd 1)

while [ -z "$nombre" ]; do
	nombre=$(dialog --inputbox "Introduzca el nombre del equipo:\n\n(Recomiendo uno de una palabra y en minuscúlas)" 0 0 --output-fd 1)
	[ -z "$nombre" ] && dialog --msgbox "No se ha escrito ningun nombre de equipo o se ha dejado vacío.\n\nEs necesario proporcionar un nombre para el equipo." 0 0
done

while [ -z "$usuario" ]; do
	usuario=$(dialog --inputbox "Introduzca el nombre de usuario:\n\n(Recomiendo uno de una palabra y en minuscúlas)" 0 0 --output-fd 1)
	[ -z "$usuario" ] && dialog --msgbox "No se ha escrito ningun nombre de usuario o se ha dejado vacío.\n\nEs necesario proporcionar un nombre de usuario." 0 0
done

while [ -z "$csu1" ] || [ "$csu1" != "$csu2" ]; do
	csu1=$(dialog --insecure --passwordbox "Introduzca la contraseña para $usuario" 0 0 --output-fd 1)
	csu2=$(dialog --insecure --passwordbox "Reintroduzca la contraseña para $usuario" 0 0 --output-fd 1)
	[ -z "$csu1" ] || [ -z "$csu2" ] && dialog --msgbox "No se ha escrito ninguna contraseña o se ha dejado vacía.\n\nEs necesario proporcionar una contraseña por motivos de seguridad." 0 0
	[ "$csu1" != "$csu2" ] && dialog --msgbox "Las contraseñas no coinciden.\n\nReinténtelo de nuevo." 0 0
done

while [ -z "$csa1" ] || [ "$csa1" != "$csa2" ]; do
	csa1=$(dialog --insecure --passwordbox "Introduzca la contraseña para el administrador" 0 0 --output-fd 1)
	csa2=$(dialog --insecure --passwordbox "Reintroduzca la contraseña para el administrador" 0 0 --output-fd 1)
	[ -z "$csa1" ] || [ -z "$csa2" ] && dialog --msgbox "No se ha escrito ninguna contraseña o se ha dejado vacía.\n\nEs necesario proporcionar una contraseña por motivos de seguridad." 0 0
	[ "$csa1" != "$csa2" ] && dialog --msgbox "Las contraseñas no coinciden.\n\nReinténtelo de nuevo." 0 0
done

while [ "$(kill -0 "$descarga" 2>/dev/null && echo 1)" = "1" ]; do
	dialog --colors --infobox "\Z4Esperando a que se terminen de instalar los paquetes esenciales." 10 60
	sleep 2
done

dialog --colors --infobox "\Z4Montando tabla del sistema de archivos" 10 60
genfstab -U /mnt >> /mnt/etc/fstab

curl -s https://raw.githubusercontent.com/pablofs02/arcarium/Principal/basis > /mnt/instalador
chmod +x /mnt/instalador
dialog --colors --msgbox "\Z4Instalanción de esenciales finalizado." 10 60

arch-chroot /mnt /instalador "$arranque" "$usuario" "$nombre" "$csa1" "$csu1" "$controlador"
