#!/bin/sh

#loadkeys es
timedatectl set-ntp true
umount /mnt 2>/dev/null
pacman -Sy --needed --noconfirm dialog

ping -c 1 google.com || (dialog --colors --title "\Z1ERROR" --msgbox "\nNo tienes conexión a internet.\n\nPara instalar el sistema operativo es necesario estar conectado a internet.\n\nPara conectarse a una red wifi use el comando:\n> iwctl --passphrase *contraseña* station wlan0 connect *wifi*\n\nPara una red cableada simplemente conecte la computadora con un cable ethernet." 0 0 && exit)
# iwctl station wlan0 get-networks

discos=$(lsblk -l | grep "disk" | awk '{print $1" "$4}')
disco=$(dialog --no-cancel --menu "Escoja el disco donde se instalará arcarium:" 0 0 0 $discos --output-fd 1)
cfdisk "/dev/$disco"

discos=$(lsblk -l | grep "part" | awk '{print $1" "$4}')
while [ -z "$arranque" ] || [ -z "$sistema" ] || [ "$arranque" = "$sistema" ]; do
	arranque=$(dialog --no-cancel --menu "Escoja una partición para almacenar el sistema de arranque:\n\n(Esta partición suele pesar entre 128MB y 512MB)" 0 0 0 $discos --output-fd 1)
	sistema=$(dialog --no-cancel --menu "Escoja una partición para almacenar el sistema operativo:\n\n(Esta partición almacenará todos los archivos y programas)" 0 0 0 $discos --output-fd 1)
	[ -z "$arranque" ] && dialog --msgbox "No se ha seleccionado ninguna partición para el sistema de arranque.\n\nEs necesario una partición de arranque para poder iniciar el sistema operativo." 0 0
	[ -z "$sistema" ] && dialog --msgbox "No se ha seleccionado ninguna partición para el sistema operativo.\n\nEs necesario una partición para el sistema operativo por obvias razones." 0 0
	[ -n "$arranque" ] && [ -n "$sistema" ] && [ "$arranque" = "$sistema" ] &&
		dialog --msgbox "Las particiones para el sistema de arranque y para el sistema operativo no pueden ser la misma.\n\nEn caso de solo haber una partición, cierre el programa con Control + C, cree las particiones con 'cfdisk /dev/{disco a partir}' y vuelva a ejecutar este programa." 0 0
done

dialog --colors --infobox "\Z4Creando sistema de archivos" 10 60
mkfs.fat -F 32 "/dev/$arranque" >/dev/null
mkfs.btrfs -f "/dev/$sistema" >/dev/null

dialog --colors --infobox "\Z4Montando partición" 10 60
mount "/dev/$sistema" /mnt

dialog --colors --infobox "\Z4Iniciando instalanción de paquetes esenciales." 10 60
curl -s https://raw.githubusercontent.com/pablofs02/arcarium/Principal/pacman.conf > pacman.conf
pacstrap -K -C pacman.conf /mnt base base-devel linux linux-firmware dhcpcd networkmanager git neovim btrfs-progs dosfstools ntfs-3g os-prober grub efibootmgr dialog 2>/dev/null >/dev/null &
descarga=$!

controlador=$(dialog --colors --menu "Escoja su targeta gráfica:" 0 0 0 \
	1 "Nvidia" \
	2 "Intel" \
	3 "AMD" \
	--output-fd 1)

while [ "$(kill -0 "$descarga" 2>/dev/null && echo 1)" = "1" ]; do
	dialog --colors --infobox "\Z4Esperando a que se terminen de instalar los paquetes esenciales." 10 60
	sleep 1
done

dialog --colors --infobox "\Z4Montando tabla del sistema de archivos" 10 60
curl -s https://raw.githubusercontent.com/pablofs02/arcarium/Principal/basis > /mnt/instalador
chmod +x /mnt/instalador
mv pacman.conf /mnt
genfstab -U /mnt >> /mnt/etc/fstab

dialog --colors --msgbox "\Z4Instalanción de esenciales finalizado." 10 60

arch-chroot /mnt /instalador "$arranque" "$usuario" "$nombre"
