#!/bin/sh

# loadkeys es
timedatectl set-ntp true
umount /mnt 2>/dev/null
pacman -Sy

#ping -c 1 google.com || (iwctl station wlan0 get-networks &&
	#read -p "Red: " red
	#read -p "Contraseña: " cs
	#iwctl --passphrase "$red" station wlan0 connect "$cs")

ping -c 1 google.com || (whiptail --title "ERROR" --msgbox "\nNo tienes conexión a internet.\n\nPara instalar el sistema operativo es necesario estar conectado a internet.\n\nPara conectarse a una red wifi use el comando:\n> iwctl --passphrase *contraseña* station wlan0 connect *wifi*\n\nPara una red cableada simplemente conecte la computadora con un cable ethernet." 16 60 && exit)

discos=$(lsblk -l | grep "disk" | awk '{print $1" "$4}')
disco=$(whiptail --nocancel --menu "Escoja el disco donde se instalará arcarium:" 16 60 0 $discos --output-fd 1)
cfdisk "/dev/$disco"
sleep 0.1

discos=$(lsblk -l | grep "part" | awk '{print $1" "$4}')
while [ -z "$arranque" ] || [ -z "$sistema" ] || [ "$arranque" = "$sistema" ]; do
	arranque=$(whiptail --nocancel --menu "Escoja una partición para almacenar el sistema de arranque:\n\n(Esta partición suele pesar entre 128MB y 512MB)" 16 60 0 $discos --output-fd 1)
	sistema=$(whiptail --nocancel --menu "Escoja una partición para almacenar el sistema operativo:\n\n(Esta partición almacenará todos los archivos y programas)" 16 60 0 $discos --output-fd 1)
	[ -z "$arranque" ] && whiptail --msgbox "No se ha seleccionado ninguna partición para el sistema de arranque.\n\nEs necesario una partición de arranque para poder iniciar el sistema operativo." 16 60
	[ -z "$sistema" ] && whiptail --msgbox "No se ha seleccionado ninguna partición para el sistema operativo.\n\nEs necesario una partición para el sistema operativo por obvias razones." 16 60
	[ -n "$arranque" ] && [ -n "$sistema" ] && [ "$arranque" = "$sistema" ] &&
		whiptail --msgbox "Las particiones para el sistema de arranque y para el sistema operativo no pueden ser la misma.\n\nEn caso de solo haber una partición, cierre el programa con Control + C, cree las particiones con 'cfdisk /dev/{disco a partir}' y vuelva a ejecutar este programa." 16 60
done

whiptail --infobox "Creando sistema de archivos" 16 60
mkfs.fat -F 32 "/dev/$arranque" >/dev/null
mkfs.btrfs -f "/dev/$sistema" >/dev/null

whiptail --infobox "Montando partición" 16 60
mount "/dev/$sistema" /mnt

whiptail --infobox "Iniciando instalanción de paquetes esenciales." 16 60
pacstrap -K /mnt base base-devel linux linux-firmware \
	dhcpcd networkmanager git neovim \
	dosfstools ntfs-3g \
	grub efibootmgr \
	fzf exa scrot socat sxhkd sxiv tree \
	mpv xclip xwallpaper zathura zathura-pdf-mupdf \
	jq vorbis-tools unrar unzip zip \
	alsa-utils brightnessctl clipmenu dunst \
	zsh zsh-syntax-highlighting dash \
	firefox-i18n-es-es gparted htop inetutils net-tools \
	newsboat perl-image-exiftool openssh \
	noto-fonts-cjk noto-fonts-emoji otf-cascadia-code ttf-liberation gnu-free-fonts \
	rustup linux-headers xorg xorg-xinit picom lxappearance xdg-user-dirs \
	pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber \
	libnotify 2>/dev/null >/dev/null &
descarga=$!

controlador=$(whiptail --nocancel --menu "Escoja su targeta gráfica:" 16 60 0 \
	1 "Nvidia" \
	2 "Intel" \
	3 "AMD" \
	--output-fd 1)

while [ -z "$nombre" ]; do
	nombre=$(whiptail --inputbox "Introduzca el nombre del equipo:\n\n(Recomiendo uno de una palabra y en minuscúlas)" 16 60 --output-fd 1)
	[ -z "$nombre" ] && whiptail --msgbox "No se ha escrito ningun nombre de equipo o se ha dejado vacío.\n\nEs necesario proporcionar un nombre para el equipo." 16 60
done

while [ -z "$usuario" ]; do
	usuario=$(whiptail --inputbox "Introduzca el nombre de usuario:\n\n(Recomiendo uno de una palabra y en minuscúlas)" 16 60 --output-fd 1)
	[ -z "$usuario" ] && whiptail --msgbox "No se ha escrito ningun nombre de usuario o se ha dejado vacío.\n\nEs necesario proporcionar un nombre de usuario." 16 60
done

while [ -z "$csu1" ] || [ "$csu1" != "$csu2" ]; do
	csu1=$(whiptail --passwordbox "Introduzca la contraseña para $usuario" 16 60 --output-fd 1)
	csu2=$(whiptail --passwordbox "Reintroduzca la contraseña para $usuario" 16 60 --output-fd 1)
	[ -z "$csu1" ] || [ -z "$csu2" ] && whiptail --msgbox "No se ha escrito ninguna contraseña o se ha dejado vacía.\n\nEs necesario proporcionar una contraseña por motivos de seguridad." 16 60
	[ "$csu1" != "$csu2" ] && whiptail --msgbox "Las contraseñas no coinciden.\n\nReinténtelo de nuevo." 16 60
done

while [ -z "$csa1" ] || [ "$csa1" != "$csa2" ]; do
	csa1=$(whiptail --passwordbox "Introduzca la contraseña para el administrador" 16 60 --output-fd 1)
	csa2=$(whiptail --passwordbox "Reintroduzca la contraseña para el administrador" 16 60 --output-fd 1)
	[ -z "$csa1" ] || [ -z "$csa2" ] && whiptail --msgbox "No se ha escrito ninguna contraseña o se ha dejado vacía.\n\nEs necesario proporcionar una contraseña por motivos de seguridad." 16 60
	[ "$csa1" != "$csa2" ] && whiptail --msgbox "Las contraseñas no coinciden.\n\nReinténtelo de nuevo." 16 60
done

while [ "$(kill -0 "$descarga" 2>/dev/null && echo 1)" = "1" ]; do
	whiptail --infobox "Esperando a que se terminen de instalar los paquetes esenciales." 16 60
	sleep 2
done

whiptail --infobox "Montando tabla del sistema de archivos" 16 60
genfstab -U /mnt >> /mnt/etc/fstab

curl -s https://raw.githubusercontent.com/pablofs02/arcarium/Principal/basis > /mnt/instalador
chmod +x /mnt/instalador
whiptail --msgbox "Instalanción de esenciales finalizado." 16 60

arch-chroot /mnt /instalador "$arranque" "$usuario" "$nombre" "$csa1" "$csu1" "$controlador"
