#!/bin/sh

arranque="$1"
usuario="$2"
dispositivo="$3"
csa="$4"
csu="$5"
controlador="$6"

dialog --colors --infobox "\Z4Montando sistema de arranque." 10 60
mkdir -p /boot/efi
mount "/dev/$arranque" /boot/efi

dialog --colors --infobox "\Z4Instalando gestor de arranque." 10 60
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB >/dev/null
grub-mkconfig -o /boot/grub/grub.cfg >/dev/null

dialog --colors --infobox "\Z4Configuración base." 10 60
echo "es_ES.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=es_ES.UTF-8" > /etc/locale.conf
echo "KEYMAP=es" >> /etc/vconsole.conf
ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime
hwclock --systohc
echo "$dispositivo" > /etc/hostname
echo "127.0.0.1    localhost
::1          localhost
127.0.1.1    $dispositivo.localdomain    localhost" >> /etc/hosts

useradd -mG wheel,storage,power,audio,video "$usuario"
echo -e "$csa\n$csa" | passwd
echo -e "$csu\n$csu" | passwd "$usuario"

systemctl enable dhcpcd.service >/dev/null
systemctl enable NetworkManager.service >/dev/null

printf "\033[34m>>> INSTALANDO CONTROLADORES\033[m\n"
[ "$controlador" = "1" ] && pacman -S --noconfirm nvidia nvidia-utils nvidia-settings nvidia-prime >/dev/null &
descarga=$!

printf "\033[34m>>> CONFIGURANDO SONIDO\033[m\n"
systemctl --user enable pipewire.socket >/dev/null
systemctl --user enable pipewire-pulse.socket >/dev/null
systemctl --user enable wireplumber.service >/dev/null

printf "\033[34m>>> CONFIGURANDO SHELL\033[m\n"
ln -sf /bin/dash /bin/sh
chsh -s /usr/bin/zsh >/dev/null
printf "\033[33mIntroduzca de nuevo la contraseña de $usuario\033[m\n"
su "$usuario" -c "chsh -s /usr/bin/zsh"

#printf "\033[34m>>> INSTALANDO GESTOR DE CLAVES\033[m\n"
#pacman -S --noconfirm gnome-keyring seahorse
printf "\033[34m>>> INSTALANDO RUST\033[m\n"
rustup default stable >/dev/null
#printf "\033[34m>>> INSTALANDO EDITORES\033[m"
#pacman -S --noconfirm gimp blender inkscape >/dev/null
#printf "\033[34m>>> INSTALANDO PAMPLINAS\033[m"
#pacman -S --noconfirm termdown cmatrix >/dev/null
# dbus-python para script

printf "\033[34m>>> BAJANDO REPOSITORIOS PROPIOS\033[m\n"
git clone https://aur.archlinux.org/paru.git >/dev/null
git clone https://github.com/pablofs02/st >/dev/null
git clone https://github.com/pablofs02/dwm >/dev/null
git clone https://github.com/pablofs02/dmenu >/dev/null
printf "\033[34m>>> INSTALANDO GESTOR DE PAQUETES AUR (paru)\033[m\n"
cd paru
makepkg -si PKGBUILD >/dev/null
printf "\033[34m>>> INSTALANDO TERMINAL (st)\033[m\n"
cd ../st
make install >/dev/null
printf "\033[34m>>> INSTALANDO GESTOR DE VENTANAS (dwm)\033[m\n"
cd ../dwm
make install >/dev/null
printf "\033[34m>>> INSTALANDO MENÚ (dmenu)\033[m\n"
cd ../dmenu
make install >/dev/null
cd /
rm -rf st dmenu dwm paru

rm /instalador

while [ "$(kill -0 "$descarga" 2>/dev/null && echo 1)" = "1" ]; do
	dialog --colors --infobox "\Z4Esperando a que se terminen de descargar el controlador." 10 60
	sleep 2
done
